# See https://pre-commit.com/ for usage and config
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [ commit ]
        language: system
        entry: ./.venv/bin/isort
        types: [ python ]

      - id: black
        name: black
        stages: [ commit ]
        language: system
        entry: ./.venv/bin/black --check
        types: [ python ]

      - id: flake8
        name: flake8
        stages: [ commit ]
        language: system
        entry: ./.venv/bin/flake8
        types: [ python ]

      - id: mypy
        name: mypy
        stages: [ commit ]
        language: system
        entry: ./.venv/bin/mypy tests/ src/
        types: [ python ]
        require_serial: true
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [ commit ]
        language: system
        entry: ./.venv/bin/pytest
        types: [ python ]
        pass_filenames: false

      - id: pytest-cov
        name: pytest
        stages: [ push ]
        language: system
        entry: ./.venv/bin/pytest --cov --cov-fail-under=100
        types: [ python ]
        pass_filenames: false
