version: "3.8"
services:
  <REPLACE>:
    env_file:
      - local.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt
      - /opt/data/postgres
    environment:
      POSTGRES_DATABASE_URL_ENV: "postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}"
    depends_on:
      - postgres
    networks:
      - local
    ports:
      - "8000:8000"

  postgres:
    env_file:
      - local.env
    image: postgres:13-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      PGPORT: "${PGPORT}"
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
    networks:
      - local

networks:
  local:
    driver: bridge
