name: "Python Analysis"

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Cache docker image
#        id: docker-image
#        uses: actions/cache@2.1.6
#        with:
#          path: ${{github.workspace}}/var/lib/docker/overlay2

      - name: Build the Docker image
        run: docker build -t local:latest .

      - name: Run isort in Docker
        run: docker run -t local:latest "isort --check tests/ src/"

      - name: Run black in Docker
        run: docker run -t local:latest "black --check tests/ src/"

      - name: Run flake8 in Docker
        run: docker run -t local:latest "flake8 tests/ src/"

      - name: Run mypy in Docker
        run: docker run -t local:latest "mypy --namespace-packages tests/ src/"
